# Dependabot will check our GitHub actions and if there will be a new version of any action
# Dependabot will create a pull request to update these.

# Set update schedule for GitHub Actions
version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
    commit-message:
      prefix: "infra:"
    labels:
      - "infrastructure"
